version: 3.8
services:
  web_app:
    container_name: web_app
    build: ./frontend/
    ports:
      - 4200:80
    depends_on:
      - java_app
  java_app:
    container_name: java_app
    build: ./backend/
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db/alura_foro?createDatabaseIfNotExist=true&serverTimezone=UTC
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root123
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: alura_foro
