spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost/alura_foro?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    expiration-minutes: ${EXPIRATION_MINUTES:2880}
    secret-key: ${SECRET_KEY:bWkgY2xhdmUgZXMgbXV5IHNlZ3VyYSAxMjM0NTY3ODkgQUJDYWJj}
