spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-calm-mud-a5hycb91.us-east-2.aws.neon.tech/alura_foro?user=alura_foro_owner&password=kU9idTJ5OZps&sslmode=require}
    #username: ${DATABASE_USERNAME:root}
    #password: ${DATABASE_PASSWORD:}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    expiration-minutes: ${EXPIRATION_MINUTES:2880}
    secret-key: ${SECRET_KEY:bWkgY2xhdmUgZXMgbXV5IHNlZ3VyYSAxMjM0NTY3ODkgQUJDYWJj}
