spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/alura_foro}
    username: ${DATABASE_USERNAME:postgresql}
    password: ${DATABASE_PASSWORD:postgresql}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    expiration-minutes: ${EXPIRATION_MINUTES:2880}
    secret-key: ${SECRET_KEY:bWkgY2xhdmUgZXMgbXV5IHNlZ3VyYQ==}
