spring:
  datasource:
    url: jdbc:mysql://localhost/alura_foro?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    expiration-minutes: ${EXPIRATION_MINUTES:2880}
    secret-key: ${SECRET_KEY:bWkgY2xhdmUgZXMgbXV5IHNlZ3VyYSAxMjM0NTY3ODkgQUJDYWJj}